//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marchine_Learning3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagenes
    {
        public string nombre { get; set; }
        public byte[] img { get; set; }
    }
}
